#@TYPE: Machine
#@NAME: BeagleBone Blue
#@DESCRIPTION: Custom lightweight configuration for the BB Blue robotics board

# 1. Inherit the base AM335x SoC architecture from meta-ti
require conf/machine/include/ti33x.inc

# 2. Define the exact Device Tree
# (Doing this here means you can delete it from your local.conf!)
KERNEL_DEVICETREE = "ti/omap/am335x-boneblue.dtb"

# 3. Hardware Features
# We REMOVE screen and touchscreen.
# We ADD wifi and bluetooth so Yocto knows to build the networking stack.
MACHINE_FEATURES = "apm usbgadget usbhost vfat ext2 wifi bluetooth alsa"

# 4. Image Types
# The Blue uses MicroSD cards or eMMC. We only need standard ext4 partitions 
# and a flashable WIC image. We explicitly drop the UBIFS NAND stuff.
IMAGE_FSTYPES += "tar.xz wic.xz"
WKS_FILE ?= "sdimage-2part.wks"

# 5. Serial Console
# The Blue uses ttyS0 for its JST debug header
SERIAL_CONSOLES = "115200;ttyS0"

# 6. Crucial Firmware
# Force Yocto to install the proprietary Texas Instruments firmware 
# required to make the WL1835MOD Wi-Fi/Bluetooth chip work.
MACHINE_EXTRA_RRECOMMENDS += "linux-firmware-wl18xx"